### ISSUE TITLE
Who can hack evowars on crazygames PC on please

### ISSUE THREAD

**Issue by buddha-3979** [MikeKonz/hi#2]
Who can hack evowars on crazygames on PC please
I need a gui and make them can hack evowars on crazygames on pc example : set rank ; set xp ; toggle month wing ; toggle week wing ; toggle day wing in general who can hack evowars on crazygames on PC pleaseeee?

**Comment by BlooketCommunity** [comment]
your seriously going again?

**Comment by BlooketCommunity** [comment]
![image](https://github.com/user-attachments/assets/04560558-a437-4a99-9a68-7084eb91f91c)
 in ``
this is from @TheAmazingAceLeo in `repo:Blooket-Council/Blooket-Cheats/`

**Comment by buddha-3979** [comment]
no, i'm close this issue. Please don't report me please
